name: CI

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build ASP.NET Core application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore HelpdeskApi/HelpdeskApi.csproj

      - name: Build application
        run: dotnet build HelpdeskApi/HelpdeskApi.csproj --configuration Release --no-restore